// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rediyoobxzfhrkrjafbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlZGl5b29ieHpmaHJrcmphZmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzYwMDksImV4cCI6MjA2NDc1MjAwOX0.yWPay6ki65ELqspJm0NrYjnivtCDIP5vhgWSXzf12g0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);